SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE VIEW [dbo].[vSalesHistory]
as
SELECT DATE, CUSTOMER, ITEM_NUMBER, ITEM_DESCRIPTION, SO_NUMBER, QUANTITY,UOM,REVENUE
FROM SalesHistory_BI_Data
GO
