CREATE TABLE [dbo].[tblMasterSchedule]
(
[DESIRED_SHIP_DATE] [datetime] NULL,
[STATUS] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINE_STATUS] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cust_Ord_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Line_No] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEMAND_BASE_ID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PART_ID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROMISE_DATE] [datetime] NULL,
[Mth] [float] NULL,
[YEAR] [float] NULL,
[CUSTOMER_ID] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDER_QTY] [float] NULL,
[SELLING_UM] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_ORDER_QTY] [decimal] (14, 4) NULL,
[MultLen] [float] NULL,
[MultUoM] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumOMults] [float] NULL,
[SetName] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SetNum] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReelType] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPEC] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Earliest_DDay] [datetime] NULL,
[WOID] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProdCode] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WOStatus] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QTY_SHPD] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastShip] [datetime] NULL,
[SOComments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WOComments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Stock_UM] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KG] [float] NULL,
[Due_By] [datetime] NULL,
[Comments] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Part_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day] [float] NULL,
[Line_Spec] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_PO_REF] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Balance] [float] NULL,
[Booked_Date] [datetime] NULL,
[Cat_Info] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Completed_Qty] [float] NULL,
[Entry_Status] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Holds] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Item_Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job_Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Line] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Line_ID] [int] NULL,
[Order_Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Org_Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Run_Date] [datetime] NULL,
[Schedule_Approved] [datetime] NULL,
[Source_Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plan_Header_Spec] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Order Quantity] [float] NULL,
[Detail_Schedule] [datetime] NULL,
[Detail_Balance] [int] NULL,
[Scheduled] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reel Header Spec] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reel Line Spec] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Packaging] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSR] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CableWeight] [float] NULL,
[Line_Tol] [float] NULL,
[Shop_Order_Status] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Stacked_On] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shop_ID] [int] NULL,
[FGItemNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordSource] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
