CREATE TABLE [dbo].[fi_fiber_length_extract_AFLPRD]
(
[Org] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Manufacturer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Family] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Item Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lot Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Locator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Data File ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Color] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Onhand Qty] [float] NULL,
[Material Cost] [money] NULL,
[Resource Cost] [money] NULL,
[Overhead Cost] [money] NULL,
[Last Transacted] [date] NULL,
[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subinventory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1310 ATTN] [decimal] (18, 4) NULL,
[1550 ATTN] [decimal] (18, 4) NULL,
[850 ATTN] [decimal] (18, 4) NULL,
[1300 ATTN] [decimal] (18, 4) NULL,
[850 BAND] [decimal] (18, 4) NULL,
[1300 BAND] [decimal] (18, 4) NULL,
[MFD 1550] [decimal] (18, 4) NULL,
[Extract Date] [date] NULL,
[Cable Cutoff] [int] NULL,
[Clad Diameter] [decimal] (18, 4) NULL,
[Clad Non-Circularity] [decimal] (18, 4) NULL,
[Coating Diameter] [decimal] (18, 4) NULL,
[Core clad Concentricity] [decimal] (18, 4) NULL,
[Fiber Cutoff] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MFD 1310nm] [decimal] (18, 4) NULL,
[Numerical Aperture] [decimal] (18, 4) NULL,
[Core Diameter] [decimal] (18, 4) NULL,
[MAC Value] [decimal] (18, 4) NULL,
[Original Length] [decimal] (18, 4) NULL,
[1625 ATTN] [decimal] (18, 4) NULL,
[POReceiptDt] [date] NULL,
[WIPIssueDT] [date] NULL,
[P O  Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor Ship Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Item Received As] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEO_CORE_AVG_T] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEO_CORE_AVG_B] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEO_CLAD_CONC_T] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEO_CLAD_CONC_B] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEO_CLAD_AVG_T] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEO_CLAD_AVG_B] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONC_2T] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONC_2B] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Consigned] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pallet_Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number] [int] NOT NULL IDENTITY(1, 1),
[DateInserted] [datetime] NULL CONSTRAINT [DF_fi_fiber_length_extract_AFLPRD_DateInserted] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[fi_fiber_length_extract_AFLPRD] ADD CONSTRAINT [PK_fi_fiber_length_extract_AFLPRD] PRIMARY KEY CLUSTERED  ([Number]) ON [PRIMARY]
GO
