CREATE TABLE [dbo].[PrintedLabelsArchive]
(
[Reel No] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order Qty] [int] NOT NULL,
[Previously Printed] [int] NULL,
[Print Now] [int] NULL,
[Completed Buffering] [int] NULL,
[Buff Line #] [smallint] NOT NULL,
[TB PRIORITY] [float] NULL,
[Setup Buff] [int] NULL,
[Setup SZ/SH] [int] NULL,
[Completed Cabling] [int] NULL,
[Make/Ship orders] [int] NULL,
[Sheathing Line #] [smallint] NULL,
[Shipped] [int] NULL,
[Close Date] [datetime] NULL,
[BOM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOM Comments] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CM Required] [int] NULL,
[Run Order] [smallint] NULL,
[Early Star Date] [int] NULL,
[Completed TightBuffer] [int] NULL,
[IASeq] [smallint] NULL,
[CabSeq] [int] NULL,
[Sh3Seq] [smallint] NULL,
[SSMA_TimeStamp] [timestamp] NOT NULL,
[DateCreatedArchiveRecord] [datetime] NULL CONSTRAINT [DF_PrintedLabelsArchive_DateCreatedArchiveRecord] DEFAULT (getdate()),
[CreatedByArchiveRecord] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PrintedLabelsArchive_CreatedByArchiveRecord] DEFAULT (suser_sname()),
[DateCreated] [datetime] NULL CONSTRAINT [DF_PrintedLabelsArchive_DateCreated] DEFAULT (getdate()),
[CreatedBy] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PrintedLabelsArchive_CreatedBy] DEFAULT (suser_sname()),
[RevisedBy] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PrintedLabelsArchive_RevisedBy] DEFAULT (suser_sname()),
[DateRevised] [datetime] NULL CONSTRAINT [DF_PrintedLabelsArchive_DateRevised] DEFAULT (getdate()),
[GUID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
