CREATE TABLE [dbo].[tblCableConstructionsARCHIVE]
(
[BaseID] [int] NOT NULL,
[CablePasses] [tinyint] NULL,
[StandardOperation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JacketMaterial] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NominalOD] [decimal] (6, 3) NULL,
[ODTolPlus] [decimal] (6, 3) NULL,
[ODTolMinus] [decimal] (6, 3) NULL,
[Height] [decimal] (6, 3) NULL,
[HeightTolPlus] [decimal] (6, 3) NULL,
[HeightTolMinus] [decimal] (6, 3) NULL,
[NominalWall] [decimal] (6, 3) NULL,
[MaxAveWall] [decimal] (6, 3) NULL,
[MinAveWall] [decimal] (6, 3) NULL,
[MinSpotWall] [decimal] (6, 3) NULL,
[AramidType1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AramidEnds1] [tinyint] NULL,
[AramidType2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AramidEnds2] [tinyint] NULL,
[ChipType] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColorChipPercentage] [numeric] (7, 5) NULL,
[Ripcord] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RipcordQty] [tinyint] NULL,
[LayLength] [decimal] (6, 3) NULL,
[Talc] [bit] NULL,
[FRP_Dia] [decimal] (6, 3) NULL,
[CM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMMaterial] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CM_OD] [decimal] (6, 3) NULL,
[CMODTolPlus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMODTolMinus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMWall] [decimal] (6, 3) NULL,
[CMMinWall] [decimal] (6, 3) NULL,
[HelixFactor] [decimal] (16, 8) NULL,
[CoreWrap] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoreDia] [decimal] (6, 3) NULL,
[Binder1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QtyBinder1] [tinyint] NULL,
[Binder1LayLength] [tinyint] NULL,
[Binder2] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QtyBinder2] [tinyint] NULL,
[Binder2LayLength] [tinyint] NULL,
[Binder3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QtyBinder3] [tinyint] NULL,
[Binder3LayLength] [tinyint] NULL,
[RevisionDate] [datetime] NULL,
[RevisionNumber] [smallint] NULL,
[RevisionHistory] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Instructions] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Instructions2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSMA_TimeStamp] [timestamp] NOT NULL,
[DateCreated] [datetime] NULL CONSTRAINT [DF_tblCableConstructionsARCHIVE_DateCreated] DEFAULT (getdate()),
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_tblCableConstructionsARCHIVE_CreatedBy] DEFAULT (suser_sname()),
[RevisedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID] [int] NULL,
[TableID] [int] NOT NULL IDENTITY(1, 1),
[Additive] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdditivePercentage] [numeric] (7, 5) NULL,
[FirstRun] [bit] NULL CONSTRAINT [DF_tblCableConstructionsARCHIVE_FirstRun] DEFAULT ((1)),
[EngineeringAssist] [bit] NULL CONSTRAINT [DF_tblCableConstructionsARCHIVE_EngineeringAssist] DEFAULT ((0)),
[TemperatureApplication] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TensileApplication] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_tblCableConstructionsARCHIVE_TensileApplication] DEFAULT ((0)),
[StandardsApplication] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblCableConstructionsARCHIVE] ADD CONSTRAINT [PK_tblCableConstructionsARCHIVE] PRIMARY KEY CLUSTERED  ([TableID]) ON [PRIMARY]
GO
DENY DELETE ON  [dbo].[tblCableConstructionsARCHIVE] TO [SPB Premise SQL RW]
GO
DENY UPDATE ON  [dbo].[tblCableConstructionsARCHIVE] TO [SPB Premise SQL RW]
GO
