CREATE TABLE [dbo].[Basic (Cable/Sheath)]
(
[New Oracle Part Number] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Item No] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Part Num] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerRev] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Active] [bit] NULL,
[Reason] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Base] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Revision Date] [datetime2] (0) NULL,
[Revision Letter] [int] NULL,
[Revision History] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSS Document #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Print Item No] [smallint] NULL,
[Print Reel No] [smallint] NULL,
[Print Height] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Print Type (base)] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Print Line 1] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Print Line 2] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Print Line 3] [nvarchar] (78) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Print Line 4] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPrintLine4] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintSpacing] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintNotes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Listing Company] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UL-ETL-Listing] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UL-ETL-Const] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UL-ETL-Section] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unit Series] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FRP Dia] [real] NULL,
[CM Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CM Matrl] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CM OD] [real] NULL,
[CM OD Tol +] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CM OD Tol -] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CM Wall] [real] NULL,
[CM Min Wall] [real] NULL,
[Binder #1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Qty Binder #1] [tinyint] NULL,
[Binder1LayLength] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Binder #2] [nvarchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Qty Binder #2] [tinyint] NULL,
[Binder2LayLength] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lay Length] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Helix Factor] [real] NULL,
[Core Wrap] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Binder #3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Qty Binder #3] [tinyint] NULL,
[Binder3LayLength] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Core Dia] [real] NULL,
[Ripcord] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jacket Material] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jacket Color] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColorChip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nom Wall] [real] NULL,
[Min Ave Wall] [real] NULL,
[Min Spot Wall] [real] NULL,
[Max Ave Wall] [real] NULL,
[Nominal OD] [real] NULL,
[OD Tol  (+)] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OD Tol  (-)] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chip Type] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiber Type A] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1st Req Freq - A] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1st Max Atten - A] [real] NULL,
[1st Min BandW - A] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2nd Req Freq - A] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2nd Max Atten - A] [real] NULL,
[2nd Min BandW - A] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiber Type B] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1st Req Freq - B] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1st Max Atten - B] [real] NULL,
[1st Min BandW - B] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2nd Req Freq - B] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2nd Max Atten - B] [real] NULL,
[2nd Min BandW - B] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiber Type C] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1st Req Freq - C] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1st Max Atten - C] [real] NULL,
[1st Min BandW - C] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2nd Req Freq - C] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2nd Max Atten - C] [real] NULL,
[2nd Min BandW - C] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Special Instr Product1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Special Instr Product2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Special Instr Product3] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Special Instr Product4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Label Type] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENumber] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[load into oracle 11?] [smallint] NULL,
[calculate bill?] [smallint] NULL,
[Standard Operation] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OracleStatus] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aramid1Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aramid1Count] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aramid2Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aramid2Count] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime2] NULL,
[CreatedBy] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevisedBy] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevisedDate] [datetime2] NULL,
[BaseID] [int] NULL,
[TimeStamp] [timestamp] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
