CREATE TABLE [dbo].[AFL_SHP_Shipments_Value_Report_260418]
(
[Org] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipped] [datetime] NULL,
[Cust Num] [bigint] NULL,
[Customer] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order Num] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer PO] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Item] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [varchar] (288) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Price] [float] NULL,
[Qty] [bigint] NULL,
[Value (BU Currency)] [float] NULL,
[UOM] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Freight Carrier] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tracking Num] [varchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Delivery Receipt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billable Tolerance Pct] [bigint] NULL,
[Customer PID] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product Class] [varchar] (76) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product Group] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location] [varchar] (52) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer PO Line] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Value (USD)] [float] NULL,
[Item Cost] [float] NULL,
[Shipment Cost] [float] NULL,
[Sales Order Type] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Reference] [varchar] (104) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Promise Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Schedule Date] [datetime] NULL,
[Cable Weigth] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suggested Reel] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reel Description] [varchar] (148) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reel Type] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lagging] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reel Weight] [bigint] NULL
) ON [PRIMARY]
GO
