CREATE TABLE [dbo].[AFLPRD_COMMON_QA_PROCESS_FY_2017_todate]
(
[Transaction Date] [datetime] NULL,
[Transaction Time] [time] NULL,
[Record Entered By] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Op Seq Number] [bigint] NULL,
[ITEM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product Class 2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiber Count] [bigint] NULL,
[STD Operation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Process] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Set Up Item] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Parent DJ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Multiple Parent DJs] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Order Number] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Multiple Sales Orders] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SO Line #] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Multiple SO Lines] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Schedule Machine] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual Machine] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cut Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QTY Requested] [bigint] NULL,
[QTY Produced] [bigint] NULL,
[Oracle Defined Line Speed] [bigint] NULL,
[Design Line Speed] [float] NULL,
[Actual Line Speed] [bigint] NULL,
[Run Time (Hrs)] [float] NULL,
[Oracle Set Up (Hrs)] [float] NULL,
[RFT ?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NCMIR #] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comments] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Estimated Cable Cost] [float] NULL,
[Premise Design Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Premise Buffer Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Creation Date] [datetime] NULL,
[Last Update Date] [datetime] NULL,
[Last Updated By] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Calendar Month] [bigint] NULL,
[Calendar Year] [bigint] NULL,
[Fiscal Month] [bigint] NULL,
[Fiscal Year] [bigint] NULL,
[Tube Size] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tube Color] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DJ Current Value] [float] NULL,
[RFT Value] [bigint] NULL,
[Days in Month] [bigint] NULL,
[OA 30 Month] [float] NULL,
[Performance] [float] NULL,
[QTS OTDR Length] [float] NULL,
[MesID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AFLPRD_COMMON_QA_PROCESS_FY_2017_todate] ADD CONSTRAINT [pk_Mes] PRIMARY KEY CLUSTERED  ([MesID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_AFLPRD_COMMON_QA_PROCESS_FY_2017_todate] ON [dbo].[AFLPRD_COMMON_QA_PROCESS_FY_2017_todate] ([Actual Machine], [JOB]) ON [PRIMARY]
GO
