CREATE TABLE [dbo].[AFLPRD_ORDDTLREPT_UPLOAD_CAB]
(
[Schedule Date] [date] NULL,
[Job Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Order] [int] NOT NULL,
[Line No] [int] NOT NULL,
[Item Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Item Description] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Promise Date] [datetime] NULL,
[Cust Number] [int] NULL,
[Customer Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order QTY(PRI)] [real] NULL,
[Order UOM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order Qty] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumOMults] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Request Date] [date] NULL,
[Stock_UM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KG] [real] NULL,
[Line Tolerance] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cust Cross Ref] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Packaging Spec] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Po Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Balance] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Booked Date] [date] NULL,
[Cat Info] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Completed Qty] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Entry Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Holds] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Item Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job Number] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order Line] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order Line ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Org Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Run Date] [datetime] NULL,
[Schedule Approved] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheduling-Quality-Shipping] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheduled] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheduling-Quality] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cut Length] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Price] [money] NULL,
[Ship Set Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateInserted] [datetime] NULL CONSTRAINT [DF_AFLPRD_ORDDTLREPT_UPLOAD_CAB_DateInserted] DEFAULT (getdate())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AFLPRD_ORDDTLREPT_UPLOAD_CAB] ADD CONSTRAINT [PK__AFLPRD_O__2C98DAF4C598FD2C] PRIMARY KEY CLUSTERED  ([Sales Order], [Line No], [Item Number]) ON [PRIMARY]
GO
