CREATE TABLE [PrintSafe].[PRINT_STRING]
(
[PRODUCTION_ORDER_NUMBER] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PRINT_STRING_PRODUCTION_ORDER_NUMBER] DEFAULT (N'newid()'),
[MATERIAL_NUMBER] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRINT_STRING_NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRINT_STRING_DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRINT_STRING] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INSERT_DATE] [datetime] NULL,
[UPDATE_DATE] [datetime] NULL,
[ITEM_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UniqueID] [uniqueidentifier] NULL CONSTRAINT [DF_PRINT_STRING_UniqueID] DEFAULT (newid()),
[DateInserted] [datetime] NULL CONSTRAINT [DF_PRINT_STRING_DateInserted] DEFAULT (getdate())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
