CREATE TABLE [tblCableConstructionReferences_Local] (
  [Base] VARCHAR (50) CONSTRAINT [PK_tblCableConstructionReferences] PRIMARY KEY  UNIQUE  NOT NULL ,
  [DateCreated] VARCHAR (27),
  [CreatedBy] VARCHAR (20),
  [RevisionDate] VARCHAR (19),
  [RevisedBy] VARCHAR (20),
  [DesignCode] VARCHAR (20),
  [DesignExtension] VARCHAR (20),
  [ConstructionDescription] VARCHAR (50),
  [BaseID] LONG ,
  [NumSubFillers] LONG ,
  [Active] BIT ,
  [PrefixID] LONG ,
  [FamilyID] LONG ,
  [FibersPerBundle] SHORT ,
  [UnitIDTypeNumber] LONG ,
  [InactiveReason] LONGTEXT ,
  [NumSubPositions] LONG ,
  [TBType] VARCHAR (20),
  [CableFamily] VARCHAR (1),
  [CableLevel1] VARCHAR (1),
  [DesignTypeID] LONG ,
  [NumCopperUnits] LONG ,
  [FiberCount] SHORT ,
  [CableType] LONGTEXT ,
  [LeadTime_ID] LONG ,
  [LeadTime_ID_Armored] LONG ,
  [ImageGroupID] LONG ,
  [ReleasedDesign] LONG ,
  [IsCommoned] LONG 
)
