CREATE TABLE [tblCableConstructions_Local] (
  [CablePasses] UNSIGNED BYTE ,
  [StandardOperation] VARCHAR (255),
  [JacketMaterial] VARCHAR (30),
  [NominalOD] VARCHAR ,
  [ODTolPlus] VARCHAR ,
  [ODTolMinus] VARCHAR ,
  [Height] VARCHAR ,
  [HeightTolPlus] VARCHAR ,
  [HeightTolMinus] VARCHAR ,
  [NominalWall] VARCHAR ,
  [MaxAveWall] VARCHAR ,
  [MinAveWall] VARCHAR ,
  [MinSpotWall] VARCHAR ,
  [AramidType1] VARCHAR (15),
  [AramidEnds1] UNSIGNED BYTE ,
  [AramidType2] VARCHAR (15),
  [AramidEnds2] UNSIGNED BYTE ,
  [ChipType] VARCHAR (15),
  [ColorChipPercentage] VARCHAR ,
  [Ripcord] VARCHAR (15),
  [RipcordQty] UNSIGNED BYTE ,
  [LayLength] VARCHAR ,
  [Talc] BIT ,
  [FRP_Dia] VARCHAR ,
  [CM] VARCHAR (50),
  [CMMaterial] VARCHAR (50),
  [CM_OD] VARCHAR ,
  [CMODTolPlus] VARCHAR (20),
  [CMODTolMinus] VARCHAR (20),
  [CMWall] VARCHAR ,
  [CMMinWall] VARCHAR ,
  [HelixFactor] VARCHAR ,
  [CoreWrap] VARCHAR (255),
  [CoreDia] VARCHAR ,
  [Binder1] VARCHAR (255),
  [QtyBinder1] UNSIGNED BYTE ,
  [Binder1LayLength] UNSIGNED BYTE ,
  [Binder2] VARCHAR (75),
  [QtyBinder2] UNSIGNED BYTE ,
  [Binder2LayLength] UNSIGNED BYTE ,
  [Binder3] VARCHAR (255),
  [QtyBinder3] UNSIGNED BYTE ,
  [Binder3LayLength] UNSIGNED BYTE ,
  [ID] AUTOINCREMENT,
  [Additive] VARCHAR (50),
  [AdditivePercentage] VARCHAR ,
  [FirstRun] BIT ,
  [EngineeringAssist] BIT ,
  [AramidType3] VARCHAR (15),
  [AramidEnds3] UNSIGNED BYTE ,
  [TemperatureApplication] VARCHAR (20),
  [TensileApplication] VARCHAR (20),
  [StandardsApplication] VARCHAR (20),
  [Additive2] VARCHAR (50),
  [AdditivePercentage2] VARCHAR ,
  [TensileRatingShortTerm_N] SHORT ,
  [TensileRatingLongTerm_N] SHORT ,
  [EngineeringAssistReason] VARCHAR (255),
  [Instructions] VARCHAR (255),
  [Instructions2] VARCHAR (255),
  [CableShapeID] LONG ,
  [FiberApplicationID] LONG ,
  [JacketStripID] LONG ,
   CONSTRAINT 
)
