CREATE TABLE [tblItemLoadTempBOM] (
  [OperationSeqNumber] LONG ,
  [ItemSeqNumber] LONG ,
  [OrganizationCode] VARCHAR (3),
  [AssemblyItemNumber] VARCHAR (30),
  [ComponentItemNumber] VARCHAR (30),
  [EffectivityDate] DATETIME ,
  [ComponentQuantity] DOUBLE ,
  [AlternateBOMDesignator] VARCHAR (10),
  [CountPerUOM] VARCHAR (150),
  [ProcessID] LONG ,
  [StdOp] VARCHAR (15),
  [OracleUOM] VARCHAR (5),
  [RawID] LONG ,
  [RawMaterialGroup] LONG ,
  [UOMConversion] DOUBLE ,
  [Layer] LONG ,
  [UnitID] LONG ,
  [Basis] VARCHAR (50),
  [SupplySubinventory] VARCHAR (50),
  [SupplyLocator] VARCHAR (50),
  [SupplyType] VARCHAR (50)
)
