CREATE TABLE [tblNewBasicCableHold] (
  [New Oracle Part Number] VARCHAR (255) CONSTRAINT [PrimaryKey] PRIMARY KEY  UNIQUE  NOT NULL ,
  [Item No] VARCHAR (50),
  [Customer] VARCHAR (255),
  [Active] BIT ,
  [Reason] VARCHAR (255),
  [Base] VARCHAR (50),
  [Revision Date] DATETIME ,
  [Revision Letter] LONG ,
  [Revision History] LONGTEXT ,
  [PSS Document #] VARCHAR (255),
  [Customer Part Num] VARCHAR (255),
  [Print Item No] BIT ,
  [Print Reel No] BIT ,
  [Print Height] VARCHAR (255),
  [Print Type (base)] VARCHAR (50),
  [Print Line 1] VARCHAR (70),
  [Print Line 2] VARCHAR (70),
  [Print Line 3] VARCHAR (70),
  [Print Line 4] VARCHAR (70),
  [NewPrintLine4] VARCHAR (70),
  [PrintSpacing] VARCHAR (255),
  [PrintNotes] VARCHAR (255),
  [Listing Company] VARCHAR (50),
  [UL-ETL-Listing] VARCHAR (50),
  [UL-ETL-Const] VARCHAR (50),
  [UL-ETL-Section] VARCHAR (50),
  [Unit Series] VARCHAR (50),
  [FRP Dia] SINGLE ,
  [CM Type] VARCHAR (255),
  [CM Matrl] VARCHAR (255),
  [CM OD] SINGLE ,
  [CM OD Tol +] VARCHAR (20),
  [CM OD Tol -] VARCHAR (20),
  [CM Wall] SINGLE ,
  [CM Min Wall] SINGLE ,
  [Binder #1] VARCHAR (255),
  [Qty Binder #1] UNSIGNED BYTE ,
  [Binder #2] VARCHAR (75),
  [Qty Binder #2] UNSIGNED BYTE ,
  [Lay Length] VARCHAR (255),
  [Helix Factor] SINGLE ,
  [Core Wrap] VARCHAR (255),
  [Binder #3] VARCHAR (255),
  [Qty Binder #3] UNSIGNED BYTE ,
  [Core Dia] SINGLE ,
  [Ripcord] VARCHAR (255),
  [Jacket Material] VARCHAR (255),
  [Jacket Color] VARCHAR (255),
  [ColorChip] VARCHAR (50),
  [Nom Wall] SINGLE ,
  [Min Ave Wall] SINGLE ,
  [Min Spot Wall] SINGLE ,
  [Max Ave Wall] SINGLE ,
  [Nominal OD] SINGLE ,
  [OD Tol  (+)] VARCHAR (5),
  [OD Tol  (-)] VARCHAR (5),
  [Chip Type] VARCHAR (30),
  [Fiber Type A] VARCHAR (255),
  [1st Req Freq - A] VARCHAR (25),
  [1st Max Atten - A] SINGLE ,
  [1st Min BandW - A] VARCHAR (25),
  [2nd Req Freq - A] VARCHAR (5),
  [2nd Max Atten - A] SINGLE ,
  [2nd Min BandW - A] VARCHAR (25),
  [Fiber Type B] VARCHAR (255),
  [1st Req Freq - B] VARCHAR (25),
  [1st Max Atten - B] SINGLE ,
  [1st Min BandW - B] VARCHAR (25),
  [2nd Req Freq - B] VARCHAR (25),
  [2nd Max Atten - B] SINGLE ,
  [2nd Min BandW - B] VARCHAR (4),
  [Fiber Type C] VARCHAR (255),
  [1st Req Freq - C] VARCHAR (5),
  [1st Max Atten - C] SINGLE ,
  [1st Min BandW - C] VARCHAR (4),
  [2nd Req Freq - C] VARCHAR (5),
  [2nd Max Atten - C] SINGLE ,
  [2nd Min BandW - C] VARCHAR (4),
  [Special Instr Product1] VARCHAR (255),
  [Special Instr Product2] VARCHAR (255),
  [Special Instr Product3] VARCHAR (60),
  [Special Instr Product4] VARCHAR (255),
  [Label Type] VARCHAR (25),
  [ENumber] VARCHAR (25),
  [load into oracle 11?] BIT ,
  [calculate bill?] BIT ,
  [Standard Operation] VARCHAR (25),
  [OracleStatus] VARCHAR (50),
  [Aramid1Type] VARCHAR (255),
  [Aramid1Count] VARCHAR (50),
  [Aramid2Type] VARCHAR (255),
  [Aramid2Count] VARCHAR (50),
  [CustomerRev] VARCHAR (50),
  [Binder1LayLength] VARCHAR (50),
  [Binder2LayLength] VARCHAR (50),
  [Binder3LayLength] VARCHAR (50),
  [VendorSpecificFiber] BIT 
)
