CREATE TABLE [tblSinglePassCable] (
  [New Oracle Part #] VARCHAR (255) CONSTRAINT [New Oracle Part #] UNIQUE ,
  [Item No] VARCHAR (255),
  [Customer] VARCHAR (255),
  [Customer Part#] VARCHAR (255),
  [CustomerRev] VARCHAR (50),
  [ActiveItem] SHORT ,
  [Reason] VARCHAR (255),
  [calculate bill?] SHORT ,
  [Base] VARCHAR (50),
  [Cable Type] VARCHAR (255),
  [Revision Date] VARCHAR (19),
  [Revision Letter] VARCHAR (255),
  [Revision History] LONGTEXT ,
  [Standard Operation] VARCHAR (255),
  [Jacket Material] VARCHAR (255),
  [Jacket Color] VARCHAR (255),
  [Color Chip ID] VARCHAR (255),
  [Print Reel No] SHORT ,
  [Print Item No] SHORT ,
  [Std Subunit Print] SHORT ,
  [Print Type (base)] VARCHAR (255),
  [Print Line 1] VARCHAR (70),
  [Print Line 2] VARCHAR (70),
  [Print Line 3] VARCHAR (70),
  [Print Line 4] VARCHAR (70),
  [NewPrintLine4] VARCHAR (70),
  [Print Spacing] VARCHAR (255),
  [PrintNotes] VARCHAR (255),
  [Listing Company] VARCHAR (255),
  [UL-ETL-Listing] VARCHAR (50),
  [UL-ETL-Const] VARCHAR (50),
  [UL-ETL-Section] VARCHAR (255),
  [ENumber] VARCHAR (255),
  [Label Type] VARCHAR (255),
  [EZ Strip] SHORT ,
  [TB Chips Type] VARCHAR (255),
  [TB Material] VARCHAR (255),
  [TB Nominal OD] VARCHAR (255),
  [TB OD Tol  (+)] VARCHAR (255),
  [TB OD Tol  (-)] VARCHAR (255),
  [TB Color Series] VARCHAR (255),
  [Fiber Type] VARCHAR (255),
  [Fiber Oracle item] VARCHAR (255),
  [FiberType2] VARCHAR (50),
  [FiberType3] VARCHAR (50),
  [1st Req Freq] VARCHAR (255),
  [1st Max Atten] DOUBLE ,
  [1st Min BandW] VARCHAR (255),
  [2nd Req Freq] VARCHAR (255),
  [2nd Max Atten] DOUBLE ,
  [2nd Min BandW] VARCHAR (255),
  [SM 1300 Max Atten] VARCHAR (255),
  [SM 1550 Max Atten] VARCHAR (255),
  [Special Instr Product1] VARCHAR (255),
  [zzSpecial Instr Product3] VARCHAR (255),
  [zzSpecial Instr Product4] VARCHAR (255),
  [zzOracle Part#] VARCHAR (255),
  [OracleStatus] VARCHAR (50),
  [DateCreated] VARCHAR (27),
  [CreatedBy] VARCHAR (50),
  [RevisedBy] VARCHAR (20),
  [RevisedDate] VARCHAR (27),
  [ActiveBase] SHORT ,
  [DesignCode] VARCHAR (50),
  [DesignExtension] VARCHAR (50),
  [StandardOperation] VARCHAR (255),
  [JacketMaterial] VARCHAR (255),
  [NominalOD] VARCHAR (255),
  [ODTolPlus] VARCHAR (255),
  [ODTolMinus] VARCHAR (255),
  [Height] VARCHAR (255),
  [HeightTolPlus] VARCHAR (255),
  [HeightTolMinus] VARCHAR (255),
  [NominalWall] VARCHAR (255),
  [MaxAveWall] VARCHAR (255),
  [MinAveWall] VARCHAR (255),
  [MinSpotWall] VARCHAR (255),
  [AramidType1] VARCHAR (255),
  [AramidEnds1] VARCHAR (255),
  [AramidType2] VARCHAR (255),
  [AramidEnds2] VARCHAR (255),
  [ChipType] VARCHAR (255),
  [Ripcord] VARCHAR (255),
  [LayLength] VARCHAR (255),
  [Talc] SHORT ,
  [FRP_Dia] SINGLE ,
  [CM] VARCHAR (255),
  [CMMaterial] VARCHAR (50),
  [CM_OD] SINGLE ,
  [CMODTolPlus] VARCHAR (20),
  [CMODTolMinus] VARCHAR (20),
  [CMWall] SINGLE ,
  [CMMinWall] SINGLE ,
  [HelixFactor] SINGLE ,
  [CoreWrap] VARCHAR (255),
  [CoreDia] SINGLE ,
  [Binder1] VARCHAR (255),
  [QtyBinder1] UNSIGNED BYTE ,
  [Binder1LayLength] VARCHAR (50),
  [Binder2] VARCHAR (75),
  [QtyBinder2] UNSIGNED BYTE ,
  [Binder2LayLength] VARCHAR (50),
  [Binder3] VARCHAR (255),
  [QtyBinder3] UNSIGNED BYTE ,
  [Binder3LayLength] VARCHAR (50),
  [CablePasses] VARCHAR (50),
  [RevisionDate] VARCHAR (19),
  [RevisionNumber] SHORT ,
  [RevisionHistory] VARCHAR (50),
  [Instructions] VARCHAR (255),
  [Instructions2] VARCHAR (255),
  [NumSubs] LONG ,
  [BaseID] LONG ,
  [Location] LONG 
)
