IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NAA\SPB Users')
CREATE LOGIN [NAA\SPB Users] FROM WINDOWS
GO
CREATE USER [NAA\SPB Users] FOR LOGIN [NAA\SPB Users]
GO
GRANT EXECUTE TO [NAA\SPB Users]
