IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NAA\SPB Premise SQL RO')
CREATE LOGIN [NAA\SPB Premise SQL RO] FROM WINDOWS
GO
CREATE USER [NAA\SPB Premise SQL RO] FOR LOGIN [NAA\SPB Premise SQL RO]
GO
GRANT EXECUTE TO [NAA\SPB Premise SQL RO]
