IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NAA\SPB spb_PREMISE_RO')
CREATE LOGIN [NAA\SPB spb_PREMISE_RO] FROM WINDOWS
GO
CREATE USER [NAA\SPB spb_PREMISE_RO] FOR LOGIN [NAA\SPB spb_PREMISE_RO]
GO
