IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NAA\SPB spb_PREMISE')
CREATE LOGIN [NAA\SPB spb_PREMISE] FROM WINDOWS
GO
CREATE USER [SPB spb_PREMISE] FOR LOGIN [NAA\SPB spb_PREMISE]
GO
GRANT EXECUTE TO [SPB spb_PREMISE]
